# Generated by Django 5.2.7 on 2025-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('creer_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
